[metadata]
name = icing_utils
version = 0.1.0
author = Hirvonen Jarkko
description = Yleiskäyttöiset funktiot jäättämisdatan hakemiseen, laskentaan ja visualisointiin
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages = find:
python_requires = >=3.8
install_requires =
    pandas>=1.3
    numpy>=1.21
    requests>=2.25
    matplotlib>=3.4
    cmocean
    chardet
    folium
    streamlit>=1.0